# Generated by Django 2.2.4 on 2019-11-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191030_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, height_field=600, null=True, upload_to='userimages', width_field=480),
        ),
    ]
