# Generated by Django 2.2.4 on 2019-11-08 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('mascotas', '0001_initial'), ('mascotas', '0002_mascota_existe'), ('mascotas', '0003_auto_20191022_1256'), ('mascotas', '0004_auto_20191027_1607'), ('mascotas', '0005_auto_20191101_1318'), ('mascotas', '0006_auto_20191101_1319'), ('mascotas', '0007_auto_20191105_1504'), ('mascotas', '0008_auto_20191105_1513'), ('mascotas', '0009_auto_20191105_1543'), ('mascotas', '0010_auto_20191105_1709'), ('mascotas', '0011_remove_mascota_infomed'), ('mascotas', '0012_auto_20191107_1811'), ('mascotas', '0013_auto_20191107_1821'), ('mascotas', '0014_auto_20191107_2101'), ('mascotas', '0015_auto_20191108_0055'), ('mascotas', '0016_auto_20191108_0109'), ('mascotas', '0017_mascota_slug')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default=0, upload_to='mascotas')),
                ('nombre', models.CharField(max_length=30)),
                ('especie', models.CharField(max_length=20)),
                ('raza', models.CharField(blank=True, max_length=20, null=True)),
                ('sexo', models.CharField(max_length=15)),
                ('existe', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fec_nac', models.DateField(default=django.utils.timezone.now)),
                ('nomb_opcional', models.CharField(blank=True, max_length=30, null=True)),
                ('ciudad_vet', models.CharField(blank=True, max_length=30, null=True)),
                ('cp_vet', models.CharField(blank=True, max_length=4, null=True)),
                ('detalles_vet', models.CharField(blank=True, max_length=200, null=True)),
                ('dir_vet', models.CharField(blank=True, max_length=50, null=True)),
                ('info_medica', models.TextField(default='No tiene', max_length=240)),
                ('nom_doc', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_vet', models.CharField(blank=True, max_length=30, null=True)),
                ('tel_vet', models.CharField(blank=True, max_length=16, null=True)),
                ('slug', models.SlugField(default=django.utils.timezone.now, unique=True)),
            ],
            options={
                'unique_together': {('usuario', 'nombre')},
            },
        ),
    ]
