# Generated by Django 2.2.7 on 2019-11-12 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mascotas')),
                ('nombre', models.CharField(max_length=30)),
                ('nomb_opcional', models.CharField(blank=True, max_length=30, null=True)),
                ('especie', models.CharField(max_length=20)),
                ('raza', models.CharField(blank=True, max_length=20, null=True)),
                ('sexo', models.CharField(max_length=15)),
                ('fec_nac', models.DateField()),
                ('existe', models.BooleanField(default=True)),
                ('info_medica', models.TextField(default='No tiene', max_length=240)),
                ('nom_doc', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_vet', models.CharField(blank=True, max_length=30, null=True)),
                ('dir_vet', models.CharField(blank=True, max_length=50, null=True)),
                ('tel_vet', models.CharField(blank=True, max_length=16, null=True)),
                ('cp_vet', models.CharField(blank=True, max_length=4, null=True)),
                ('ciudad_vet', models.CharField(blank=True, max_length=30, null=True)),
                ('detalles_vet', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'nombre')},
            },
        ),
    ]
