# Generated by Django 2.2.4 on 2019-11-08 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_squashed_0017_mascota_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fec_nac',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(upload_to='mascotas'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
