# Generated by Django 2.2.4 on 2019-12-13 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_auto_20191027_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perdidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=50)),
                ('b', models.DateField()),
                ('c', models.CharField(blank=True, max_length=50, null=True)),
                ('d', models.CharField(blank=True, max_length=50, null=True)),
                ('e', models.BooleanField(default=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.Mascota')),
            ],
        ),
    ]
