# Generated by Django 2.2.4 on 2019-11-01 16:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_auto_20191027_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='dir_veterinaria',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='info_medica',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='veterinaria',
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_nac',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(max_length=2),
        ),
        migrations.CreateModel(
            name='InfoMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_medica', models.TextField(max_length=200)),
                ('nom_doc', models.CharField(blank=True, max_length=30, null=True)),
                ('nom_vet', models.CharField(blank=True, max_length=20, null=True)),
                ('dir_vet', models.CharField(blank=True, max_length=35, null=True)),
                ('tel_vet', models.CharField(blank=True, max_length=10, null=True)),
                ('cp_vet', models.CharField(blank=True, max_length=4, null=True)),
                ('ciudad_vet', models.CharField(blank=True, max_length=15, null=True)),
                ('detalles_vet', models.CharField(blank=True, max_length=200, null=True)),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mascotas.Mascota')),
            ],
        ),
    ]
