# Generated by Django 2.2.4 on 2019-11-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0006_auto_20191101_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(height_field=600, upload_to='mascotas', width_field=480),
        ),
    ]
