# Generated by Django 2.2.4 on 2019-11-05 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0007_auto_20191105_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infomedica',
            name='mascota',
        ),
        migrations.AddField(
            model_name='mascota',
            name='infomed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mascotas.InfoMedica'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(upload_to='mascotas'),
        ),
    ]
