# Generated by Django 2.2.4 on 2019-11-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0008_auto_20191105_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='edad',
        ),
        migrations.AddField(
            model_name='mascota',
            name='nomb_opcional',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
