# Generated by Django 2.2.4 on 2019-11-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0009_auto_20191105_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='fecha_nac',
            new_name='fec_nac',
        ),
    ]
