# Generated by Django 2.2.4 on 2019-11-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0010_auto_20191105_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='infomed',
        ),
    ]
