# Generated by Django 2.2.4 on 2019-11-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0013_auto_20191107_1821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoMedica',
        ),
        migrations.AddField(
            model_name='mascota',
            name='ciudad_vet',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='cp_vet',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='detalles_vet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='dir_vet',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='info_medica',
            field=models.TextField(default='No tiene', max_length=200),
        ),
        migrations.AddField(
            model_name='mascota',
            name='nom_doc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='nom_vet',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tel_vet',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
