# Generated by Django 2.2.4 on 2019-11-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0014_auto_20191107_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='info_medica',
            field=models.TextField(default='No tiene', max_length=240),
        ),
    ]
