# Generated by Django 2.2.4 on 2019-11-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0015_auto_20191108_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='ciudad_vet',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='dir_vet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nom_doc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nom_vet',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tel_vet',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
