# Generated by Django 2.2.4 on 2019-11-08 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0016_auto_20191108_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
